# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Klama < Formula
  desc "AI-powered CLI assistant for troubleshooting DevOps-related issues."
  homepage "https://github.com/eliran89c/klama"
  version "0.1.2"

  on_macos do
    on_intel do
      url "https://github.com/eliran89c/klama/releases/download/v0.1.2/klama_Darwin_x86_64.tar.gz"
      sha256 "97c61404f3dbf08c9b685eda10debd1182b78f18e354e222dfee1e4dfb7ac029"

      def install
        bin.install "klama"
      end
    end
    on_arm do
      url "https://github.com/eliran89c/klama/releases/download/v0.1.2/klama_Darwin_arm64.tar.gz"
      sha256 "fbe40b5907193547fdf391ac393c3ecfaee5accc79206df3e16a12a6a693f413"

      def install
        bin.install "klama"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/eliran89c/klama/releases/download/v0.1.2/klama_Linux_x86_64.tar.gz"
        sha256 "2b56560ba9ad3b7da4567b8a65484ccfd89af7b478ba59166a6895e833e5f283"

        def install
          bin.install "klama"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/eliran89c/klama/releases/download/v0.1.2/klama_Linux_arm64.tar.gz"
        sha256 "8ee80898646107ebbbf44c4d5c6f60ee28a2637aa3965af22ac3bcbb96a642ad"

        def install
          bin.install "klama"
        end
      end
    end
  end

  test do
    system "#{bin}/klama version"
  end
end
