# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class S3pitr < Formula
  desc "A simple CLI tool to generate S3 bucket inventory reports."
  homepage "https://github.com/eliran89c/s3pitr"
  version "1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/eliran89c/s3pitr/releases/download/v1.1/s3pitr_Darwin_x86_64.tar.gz"
      sha256 "eb72d1772b27a61e465eebaa61ac28afc0c41f1a31632fbe54cb71c0d403259b"

      def install
        bin.install "s3pitr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/eliran89c/s3pitr/releases/download/v1.1/s3pitr_Darwin_arm64.tar.gz"
      sha256 "c6d94984f87a400d5efa588386b569a078ad6f68da20a51db93e1ec7dedcc66e"

      def install
        bin.install "s3pitr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/eliran89c/s3pitr/releases/download/v1.1/s3pitr_Linux_x86_64.tar.gz"
        sha256 "c5ed3c17ead697b344f704fe75975af64107980322d25663419bfad1b7a39b7a"

        def install
          bin.install "s3pitr"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/eliran89c/s3pitr/releases/download/v1.1/s3pitr_Linux_arm64.tar.gz"
        sha256 "1bcff6687e0735358f48aac875f9a62e28606431b2ef1c638cbd6bf5cddd5790"

        def install
          bin.install "s3pitr"
        end
      end
    end
  end

  test do
    system "#{bin}/s3pitr -version"
  end
end
