# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tagpatrol < Formula
  desc "Validate cloud resource tags against a defined policy."
  homepage "https://github.com/eliran89c/tag-patrol"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/eliran89c/tag-patrol/releases/download/v0.2.0/tag-patrol_Darwin_x86_64.tar.gz"
      sha256 "ff873c13b42b86d9a8dc309fb6fb719a418cf6f68a1890a8ba80eb878d3a827e"

      def install
        bin.install "tagpatrol"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/eliran89c/tag-patrol/releases/download/v0.2.0/tag-patrol_Darwin_arm64.tar.gz"
      sha256 "f25b4ba7bd0689e466dff7242495005f9eb5073106b563a16c5ebf6aa5093d40"

      def install
        bin.install "tagpatrol"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/eliran89c/tag-patrol/releases/download/v0.2.0/tag-patrol_Linux_x86_64.tar.gz"
      sha256 "c601b3a8d28f28f1a4e726e49f6481324920095ecdfd2cf478c07cf33d005db1"
      def install
        bin.install "tagpatrol"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/eliran89c/tag-patrol/releases/download/v0.2.0/tag-patrol_Linux_arm64.tar.gz"
      sha256 "7a42e19d3d94a62c8e50a52964798d6cb9e72a77a8cb7f71ab634b219720f3e7"
      def install
        bin.install "tagpatrol"
      end
    end
  end

  test do
    system "#{bin}/tagpatrol version"
  end
end
